version: '3'

services:
  app:
    restart: always
    build: ./

    #command: >
    #  bash -c "python wait_for_postgres.py &&
    #           ./manage.py migrate &&
    #           ./manage.py runserver 0.0.0.0:8000"
    #command: >
    #   bash -c "./manage.py migrate &&
    #            ./manage.py runserver 0.0.0.0:8000"
    #command: gunicorn -w 4 -b 0.0.0.0:8000 --chdir=/app {{ cookiecutter.app_name }}.wsgi:application

    volumes:
      - ./:/app
      - static-volume:/app/static
      - media-volume:/app/media
    depends_on:
      - postgres
      - redis
    env_file: .env

  nginx:
    image: nginx:1.14-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static-volume:/static/
      - media-volume:/media/
    depends_on:
      - app

  postgres:
    image: postgres:10.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 1900:5432
    env_file: .env

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis_data:/data
volumes:
  db-data:
  redis_data:
  static-volume:
  media-volume:

