version: '3'

services:
  postgres:
    image: postgres:10.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env

  app:
    restart: always

    image: app
    build: ./
    #    command: >
    #      bash -c "python wait_for_postgres.py &&
    #               ./manage.py migrate &&
    #               ./manage.py runserver 0.0.0.0:8000"
    #    command: >
    #       bash -c "./manage.py migrate &&
    #                ./manage.py runserver 0.0.0.0:8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 {{ cookiecutter.app_name }}.wsgi
  volumes:
    - ./:/app
    depends_on:
      - postgres
    env_file: .env

  nginx:
    image: nginx:1.14-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/production.conf:/etc/nginx/nginx.conf:ro
      - ./media:/media/
      - ./static:/static/
    depends_on:
      - app
volumes:
  db-data:

